swagger: "2.0"

info:
  title: "My first API"
  version: "1.0"

basePath: /v1.0

paths:
  /items/:
    get:
      responses:
        '200':
          description: 'Fetch a list of items'
          schema:
            type: array
            items:
              $ref: '#/definitions/Item'
  /lemmas/:
    post:
      operationId: api.lemmas.lemmatize
      parameters:
        - name: search_string
          in: query
          type: string
          required: true
          description: User request string
      responses:
        '201':  
          description: Lemmatezer request
          schema:
            $ref: '#definitions/lemmaString'
  /predict/:
    post:
      operationId: api.predict.predict_service_id
      parameters:
        - name: search_string
          in: query
          type: string
          required: true
          description: User request string
      responses:
        '202':
          description: serviceId
          schema:
            $ref: '#definitions/serviceId'
definitions:
  Item:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name: { type: string }
  lemmaString:
    type: object
    properties:
      lemma: {type: string}
  serviceId:
    type: object
    properties:
      serivce_id: {type: integer}
      service_name: {type: string}